apiVersion: apps/v1
kind: Deployment
metadata:
  name: saloon
spec:
  selector:
    matchLabels:
      app: saloon
  replicas: 3
  template:
    metadata:
      labels:
        app: saloon
    spec:
      containers:
      - name: saloon
        image: claudiugurita/saloon
        ports:
        - containerPort: 8080

